version: "3"

services:
  app:
    image: node:10.7
    depends_on:
      - postgres
    ports:
      - "2700:2700"
    volumes:
      - ./:/app
    working_dir: /app
    entrypoint: >
      bash -c "npm i && ./node_modules/.bin/nodemon ./server/index.js"

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: open-cron-monitor
      POSTGRES_DB: open-cron-monitor
      POSTGRES_PASSWORD: open-cron-monitor
